FROM node:22
WORKDIR /
COPY ["--exclude=.git", "--exclude=.gitignore", "--exclude=node_modules", "--exclude=.env", "--exclude=src"] . .
RUN npm install --production
EXPOSE 3000
CMD ["node", "run", "start"]